### ISSUE TITLE
[Question] Differences between the two current BepInEx Valheim Packs?

### ISSUE THREAD

**Issue by spannerman79** [U-1F31A/BepInEx_Valheim_Full#4]
Hi,

I'll keep this short and sweet. What are the _actual_ differences between https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full/ & https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/ ?

As far as I can tell from looking at the outside both packs pack the unstripped dll's.  Both have linux setups ( major thanks from an actual linux user - both desktop and server).  So what is actually different?

Backstory;

I'm using a docker image ( https://github.com/mbround18/valheim-docker ) which so far is the only one that has actual mod support.  And one of the questions asked was this one. ( reference: https://github.com/mbround18/valheim-docker/issues/272#issuecomment-796149050 ).

Thanks for your time.

**Comment by spannerman79** [comment]
Never mind, I actually managed to come across https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full_Updater/#reasoning:~:text=Reasoning,GitHub%20if%20you%20encounter%20any%20problems

Please ignore.

Keep issue around for search purposes just in case for others :-)

**Comment by sebastienvercammen** [comment]
Hey @spannerman79, glad to see you found the answer to your question pretty quickly! If you've got more questions, don't hesitate to ask.
